services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=nifi
      - POSTGRES_USER=nifi
      - POSTGRES_DB=nifi
