services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'nifi'
      MYSQL_USER: 'nifi'
      MYSQL_PASSWORD: 'nifi'
      MYSQL_ROOT_PASSWORD: 'nifi'
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql
