services:
  nginx:
    hostname: nginx
    container_name: nginx
    image: nginx
    depends_on:
      - nifi
    ports:
      - "8080:8080"
      - "9092:9092"
    networks:
      - default
    configs:
      - source: proxy
        target: /etc/nginx/conf.d/proxy.conf
  zookeeper:
    hostname: zookeeper
    container_name: zookeeper
    image: 'bitnami/zookeeper:latest'
    ports:
      - 2181
    networks:
      - default
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  nifi:
    image: apache/nifi:latest
    depends_on:
      - zookeeper
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: vip
    expose:
      - 8080
      - 8083
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
      - NIFI_SENSITIVE_PROPS_KEY=3e38a10eb5fb
configs:
  proxy:
    file: ./conf/proxy.conf
